<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nodedb2"
 *
 * Auto generated by Extension Builder 2014-03-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Node Database 2',
	'description' => 'A node database for wireless mesh networks like Freifunk. Written for Freifunk Augsburg.',
	'category' => 'plugin',
	'author' => 'Manuel Munz',
	'author_email' => 'freifunk@somakoma.de',
	'author_company' => 'comuno.net',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>